"use client"

export default function HeroText(){
    return (
        <div className="bg-[#FFFFFFA1] w-[80%] h-[50%] sm:h-auto sm:w-[600px] rounded-3xl px-4 py-1 sm:px-10 sm:py-5 top-40 sm:top-40 absolute overflow-hidden">
            <h1 className="text-black text-2xl sm:text-4xl mb-5">Beyond Borders, Beyond Limits, Football Unites Us All</h1>
            <p className="text-xs text-black">European football is a vibrant and competitive landscape, centered around prestigious competitions like the UEFA Champions League and the Europa League, which showcase the continent's top clubs. Major domestic leagues, including England's Premier League, Spain's La Liga, Germany's Bundesliga, Italy's Serie A, and France's Ligue 1, feature iconic teams like Real Madrid, Bayern Munich, and Manchester City, along with star players such as Lionel Messi and Kylian Mbappé. The influence of financial fair play regulations, investment in youth academies, and the integration of technology like VAR are shaping the future of the sport. With a growing global fanbase and upcoming events like the UEFA European Championship, European football continues to captivate audiences around the world. European football is a dynamic and multifaceted realm, characterized by its rich history and intense rivalries. At its core are elite competitions such as the UEFA Champions League, where top clubs from various leagues battle for supremacy, and the Europa League, which offers additional opportunities for teams to shine on the continental stage. Major leagues like the Premier League, La Liga, Bundesliga, Serie A, and Ligue 1 not only showcase footballing talent but also draw massive audiences, reflecting the sport's global appeal. Clubs are investing heavily in youth development and scouting to secure the next generation of stars, while financial fair play regulations aim to maintain competitive balance. The introduction of technologies like VAR has transformed match officiating, adding another layer of intrigue.</p>
        </div>
    )
}